### ISSUE TITLE
knitr engine doesn't capture python stdout

### ISSUE THREAD

**Issue by t-kalinowski** [rstudio/reticulate#1387] opened 2023-06-07 13:13 UTC
Rendering a quarto doc with two chunks like this produces no output:
````
```{python}
def print_something():
    print("Hello")
```

```{r}
py$print_something()
```
````

**Comment by matthew-brett** [comment] 2023-06-28 22:11
I just noticed this too - in this case after enabling `jupyter_compat`.  Consider the output from `rmarkdown::render('test.Rmd', output_format='md_document')` on `test.Rmd`:

~~~
```{python, jupyter_compat=TRUE}
print(1)
print(2)
```

~~~

The result is `test.md`:

~~~
    print(1)
    print(2)

    ## 2
~~~

**Comment by dfalbel** [comment] 2023-07-10 12:05
I'm guessing this is caused by `capture.output` not really cathing the Python output, eg:

```
length(capture.output(py$print_something()))
#> [1] 0
#> Hello
```

**Comment by dfalbel** [comment] 2023-07-10 20:37
Ok, so finding a bit more context. It seems this issue is actually a duplicate of #331 
Particularly I found an interesting discussions here https://github.com/rstudio/rstudio/issues/3271#issuecomment-422818610 and here: https://github.com/rstudio/reticulate/pull/314#issuecomment-412400050

The main arguments are:
 
- the problem with calling external functions not necessarily mapping to the R stdout is not exclusive to reticulate, for instance `system("echo 'hello world'")` yields similar behavior. So that's not necessarily the expected behavior.
- Always remapping the streams can lead to unexpected problems, specially if calling R from Python (leading to an infinite recursion). Other unexpected behaviors could be caused by changing this.

If we decide to move with always remapping, we should make sure that `py_capture_output` works correctly. Currently, it breaks after the remapping - seems to be related usages of the python standard logger. But could potentially cause issues in other cases.

**Closed** 2023-07-18 12:36 UTC

**Comment by matthew-brett** [comment] 2023-07-21 14:58
Sorry to piggy-back on this one - but I notice I still have the same behavior on current `main` as before - the `jupyter_compat` option will throw away stdout.   I guess this means I have to work out how to distinguish stdout from other output in the intermediate code lines - say around here : https://github.com/rstudio/reticulate/blob/main/R/knitr-engine.R#L213 . Can y'll recommend any way to do that?
