### ISSUE TITLE
'memory not mapped' segfault using rpy2 and reticulate

### ISSUE THREAD

**Issue by matthewgasbarro** [rstudio/reticulate#1112] opened 2022-01-04 17:32 UTC
I have R 4.0.4 installed in a Debian 11 (bullseye) slim docker container. I have a Jupyter notebook opened using IRkernel that has reticulate library loaded and is calling a python script using the reticulate method py_run_file After several executions of the Jupyter cell I receive a segfault error with message  'memory not mapped'.

The issue is similar to following issues but with different segfault error, and simpler steps to reproduce
[#98](https://github.com/rstudio/reticulate/issues/98)
[#104](https://github.com/rstudio/reticulate/pull/104)
[#138](https://github.com/rstudio/reticulate/issues/138)
[#208](https://github.com/rstudio/reticulate/issues/208)

Steps to Reproduce

Given a Jupyter environment with following packages installed:

R Packages installed are:
R 4.0.4
IRkernel 1.3
reticulate 1.22
IRdisplay 1.1

Python Packages installed are:
python = "3.8.12"
rpy2 = "3.4.5"
notebook = "6.4.3"

1. Create test_IRdisplay.py file with content:
`from rpy2.robjects.packages import importr rdisplay = importr('IRdisplay') rdisplay.display_html('<h1>Hi</h1>')`
2. Upload test_IRdisplay.py file to Jupyter
3. Open new R notebook in Jupyter
4. Type in a cell `library(reticulate) py_run_file("test_IRdisplay.py")`
5. Execute cell repeatedly until Dead Kernel error (for me the error occurs between 5-15th try)

Logs show:
`*** caught segfault *** address 0xb8, cause 'memory not mapped' An irrecoverable exception occurred. R is aborting now ...`

I do see this warning after the first time the cell is executed:
`/usr/local/lib/python3.8/site-packages/rpy2/rinterface_lib/embedded.py:134: UserWarning: R was initialized outside of rpy2 (R_NilValue != NULL). Trying to use it nevertheless. warnings.warn(`

**Comment by t-kalinowski** [comment] 2022-01-04 18:48
Hi, thanks for reporting. To reproduce this we'd need to know how the individual components are being installed. 
Where are R and Python installed from? How are you creating the Jupyter environment?

**Comment by matthewgasbarro** [comment] 2022-01-05 15:09
Sure. I can simplify the steps to reproduce by using Jupyter's own provided R docker image

1. Create this Dockerfile:
`FROM jupyter/r-notebook

RUN 
R -e "install.packages('IRkernel',repos = 'http://cran.us.r-project.org'); if (! library(IRkernel, logical.return=T)) quit(status=10)"  && \
R -e "install.packages('reticulate',repos = 'http://cran.us.r-project.org'); if (! library(reticulate, logical.return=T)) quit(status=10)" && \
R -e "install.packages('IRdisplay',repos = 'http://cran.us.r-project.org'); if (! library(IRdisplay, logical.return=T)) quit(status=10)"

RUN pip install rpy2==3.4.5`

2. Build the docker image from same folder as Dockerfile: `docker build . --tag jupyter/r-notebook:segfault`
3. Run the image: `docker run -p 8888:8888 jupyter/r-notebook:segfault`
4. In the output that follows copy/paste into a browser the link that starts with: `http://127.0.0.1:8888/?token=...`
5. In Jupyter upload the file test_IRdisplay.py with content:
`from rpy2.robjects.packages import importr rdisplay = importr('IRdisplay') rdisplay.display_html('<h1>Hi</h1>')`
6. Open a new R notebook and type: `library(reticulate) py_run_file("test_IRdisplay.py")`
7. Execute the cell until the Dead kernel error appears and check the log output from the terminal where the image was run. You should see: 
`/opt/conda/lib/python3.9/site-packages/rpy2/rinterface_lib/embedded.py:134: UserWarning: R was initialized outside of rpy2 (R_NilValue != NULL). Trying to use it nevertheless.
  warnings.warn(

 *** caught segfault ***
address 0xb8, cause 'memory not mapped'
An irrecoverable exception occurred. R is aborting now ...`

**Comment by matthewgasbarro** [comment] 2022-02-08 02:46
any update on this issue? thanks

**Comment by t-kalinowski** [comment] 2022-02-08 20:38
Hi, I followed the instructions but was unable to reproduce the segfault:
![image](https://user-images.githubusercontent.com/8462255/153071267-10464f1a-2e0f-4778-905c-2890cf50d32a.png)

As an aside, this warning: 
> UserWarning: R was initialized outside of rpy2 (R_NilValue != NULL).

Is coming from rpy2, not reticulate. Reticulate doesn't mind if python is initialized outside of R (see https://github.com/randy3k/rchitect for an example usage). I suggest you file an issue on rpy2.

**Comment by lgautier** [comment] 2022-03-05 15:40
@t-kalinowski 

> As an aside, this warning:
>
>>    UserWarning: R was initialized outside of rpy2 (R_NilValue != NULL).
>
> Is coming from rpy2, not reticulate. Reticulate doesn't mind if python is initialized outside of R (see https://github.com/randy3k/rchitect for an example usage). I suggest you file an issue on rpy2.

rpy2 does not mind if R was initialized outside of itself. It issues a warning because this is usually the root of a long standing issue with `reticulate`:  https://github.com/rstudio/reticulate/issues/208#

My understanding is that rchitect is monkey patching reticulate with a fix that should be integrated upstream (that is in `reticulate`).

**Comment by t-kalinowski** [comment] 2022-04-22 13:26
Closed via #1188

**Comment by matthewgasbarro** [comment] 2022-05-15 20:15
I have updated to reticulate 1.25 but the issue is still reproducible using the steps I outlined in https://github.com/rstudio/reticulate/issues/1112#issuecomment-1005769087 above after executing the jupyter cell multiple times (sometimes only a handful, sometimes more than 10)

` *** caught segfault ***
address 0xb8, cause 'memory not mapped'
An irrecoverable exception occurred. R is aborting now ...`

I noticed that in your attempt to reproduce the issue, you were using R 4.1.2 and in a jupyter console where as I am using R 4.0.4 in a jupyter notebook.

**Comment by t-kalinowski** [comment] 2022-05-16 12:48
Thanks for reporting, I will investegate and try to reproduce the segfault with R 4.0.

**Comment by lgautier** [comment] 2022-05-21 16:24
Closing the loop here as well. The recent changes by @t-kalinowski andmerged in the main dev branch for `reticulate` appear to solve the issue. I have not tested this in further depth than checking that the sequence `Python->rpy2->reticualte->Python` is working, but closing this issue as resolved should be considered.

**Comment by ekianjo** [comment] 2022-06-02 04:01
@lgautier how did you try the dev branch? I'm still facing crash issues with the most recent reticulate release.

**Comment by hx07-code** [comment] 2024-07-15 06:33
It seems not the problem of reticulate or rpy2 neither. I crushed with the " *** caught segfault ***address 0x702000, cause 'memory not mapped'" either when I installed package "sf" and "units". This problem was fixed after re-compile the "Rcpp" on my current enviroment. I guess it was caused by the c++ when you using Rcpp from different enviroment.

**Comment by t-kalinowski** [comment] 2024-07-15 12:53
@hx07-code, thank you for the update!

I believe the segfault described in this issue has been resolved. If anyone is still experiencing a segfault today, it's likely due to a different cause. Should you encounter a segfault, please open a new issue with detailed instructions on how to reproduce it, and we'll do our best to assist you.

**Closed by t-kalinowski** 2024-07-15 12:53 UTC
