### ISSUE TITLE
`source_python()` unexpected input "errors"

### ISSUE THREAD

**Issue by chainsawriot** [rstudio/reticulate#1328] opened 2023-01-25 15:47 UTC
I encountered this problem with `source_python` in several Ubuntu platforms (including the ones from Github Actions). It raises errors (enough to stop `testthat`) but it actually won't stop `source_python`. In the following example, the function `one` is actually available.

Digging into it with the debugger shows that the "errors" are raised in this line

https://github.com/rstudio/reticulate/blob/3bbc5b3a80088a812315f980c9f640b7eda226f7/R/source.R#L42

when `name` is "r" and `main_dict[[name]]` is unpacking.

I am creating another reprex with Github Actions.

``` r
test_py <- "
import os
def one():
\treturn(1)
"

temppy <- tempfile(fileext = ".py")
writeLines(test_py, temppy)
reticulate::source_python(temppy)
#> Error in parse(text = as_r_value(code)): <text>:1:2: unexpected input
#> 1: __
#>      ^
#> Error in parse(text = as_r_value(code)): <text>:1:2: unexpected input
#> 1: __
#>      ^
"one" %in% ls()
#> [1] TRUE
sessionInfo()
#> R version 4.2.2 Patched (2022-11-10 r83330)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 22.04.1 LTS
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0
#> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=de_DE.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>  [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.10       pillar_1.8.1      compiler_4.2.2    highr_0.9        
#>  [5] R.methodsS3_1.8.2 R.utils_2.12.0    tools_4.2.2       digest_0.6.30    
#>  [9] jsonlite_1.8.4    evaluate_0.15     lifecycle_1.0.3   tibble_3.1.8     
#> [13] R.cache_0.16.0    lattice_0.20-45   pkgconfig_2.0.3   png_0.1-8        
#> [17] rlang_1.0.6       reprex_2.0.1      Matrix_1.5-1      cli_3.6.0        
#> [21] yaml_2.3.7        xfun_0.31         fastmap_1.1.0     withr_2.5.0      
#> [25] styler_1.7.0      stringr_1.4.1     knitr_1.39        rappdirs_0.3.3   
#> [29] fs_1.5.2          vctrs_0.5.2       rprojroot_2.0.3   grid_4.2.2       
#> [33] reticulate_1.27   glue_1.6.2        here_1.0.1        fansi_1.0.4      
#> [37] rmarkdown_2.14    purrr_1.0.1       magrittr_2.0.3    htmltools_0.5.3  
#> [41] utf8_1.2.2        stringi_1.7.12    R.oo_1.25.0
```

<sup>Created on 2023-01-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by chainsawriot** [comment] 2023-01-25 16:14
This is the minimal example

https://github.com/chainsawriot/reticulatebug/blob/v0.0/tests/testthat/test_reticulate.R

And the GHA checks, the same "errors"

https://github.com/chainsawriot/reticulatebug/actions/runs/4007745757/jobs/6881011052

**Comment by nimanouri-nn** [comment] 2023-01-25 21:09
-- Same error, in my docker, but strangely it sources the functions fine.
-- Using an older version does not make this error disappear.

**Comment by astayleraz** [comment] 2023-01-25 22:31
Im seeing this error in the console running a basic python file. This is OS ubuntu20 2023.03.0-daily+272

<img width="1364" alt="Screen Shot 2023-01-25 at 2 25 45 PM" src="https://user-images.githubusercontent.com/1482677/214706414-1348c3ea-d053-487f-908d-b5bf9aaf9fc8.png">

**Comment by t-kalinowski** [comment] 2023-01-26 02:47
Thanks for the great reprex. I can reproduce if reticulate is built with Rcpp 1.0.10. Rolling back Rcpp to 1.0.9 and rebuilding reticulate makes the error go away. 

I'll take a closer look try to figure out what the root cause is.

**Comment by t-kalinowski** [comment] 2023-01-26 17:51
The error is raised when `source_python()` attempts to export all the objects from python `__main__` to an R environment, `globalenv()` in most situations. 

As part of this, reticulate accesses `__main__.__dict__.r`, and implicitly calls `py_to_r()` on it.

In turn, `py_to_r()` calls `py_is_callable()` here https://github.com/rstudio/reticulate/blob/778909ea18114f5d3562d3801203f2c7ea7eb92b/src/python.cpp#L1063

which calls `PyObject_HasAttrString` with `__call__` here, https://github.com/rstudio/reticulate/blob/778909ea18114f5d3562d3801203f2c7ea7eb92b/src/python.cpp#L737

which calls `PyObject_GetAttrString` 

https://github.com/python/cpython/blob/7b20a0f55a16b3e2d274cc478e4d04bd8a836a9f/Objects/object.c#L791

which calls this R function with `__call__` as the object name being resolved, https://github.com/rstudio/reticulate/blob/778909ea18114f5d3562d3801203f2c7ea7eb92b/R/python.R#L1367-L1371

which attempts to `eval(parse(text = "__call__"), envir)`, which errors (because `__call__` is not a valid R symbol, but also, past that hurdle, it'll fail because `__call__` is not an R object that exists in `envir`).  

I'm not sure what this has to do with the 1.0.10 Rcpp release from 4 days ago, or why rolling back Rcpp to version 1.0.9 fixes this. Looking at the Rcpp release diff, nothing obvious to my eyes jumps out. https://github.com/cran/Rcpp/compare/1.0.9...1.0.10

I'll work on adding a narrow fix for this in reticulate. But I have a slightly uneasy that I haven't fully diagnosed the issue, because I don't see the connection to the Rcpp release. 
@eddelbuettel or @kevinushey do you have any guesses?

**Comment by kevinushey** [comment] 2023-01-26 18:21
Possibly related to the use of unwind-protect by default?

https://github.com/cran/Rcpp/compare/1.0.9...1.0.10#diff-91c5b46dc84a94604a4e4d0caed9bf85590a2eddbb12d2e8dc80badf324a9dfbR82-R84

`jsonlite` ran into a similar-ish issue, I think... https://github.com/RcppCore/Rcpp/issues/1227#issuecomment-1198123811

**Comment by eddelbuettel** [comment] 2023-01-26 18:45
Uggh.  And that's why I spend so much time on reverse depends, but as time is finite (and it currently takes 48 hrs on the old hardware) of course I do not get to recursive depends.

**Comment by t-kalinowski** [comment] 2023-01-26 18:55
Thank you both. I think this is the same type of issue as discussed in the thread Kevin linked. I confirmed that with the previous Rcpp version, the same code path is exercised by reticulate.

Only difference is that Rcpp used to silently catch the error raised by that R function, and now it doesn't. I think that's correct, and agree this is not an Rcpp issue. 

I'll work on a patch, aiming to `raise AttributeError` from the R function (this touches https://github.com/rstudio/reticulate/issues/1304 too, may be a little tricky).

**Closed** 2023-01-27 18:16 UTC
