### ISSUE TITLE
Truncated stack trace

### ISSUE THREAD

**Issue by kdkavanagh** [rstudio/reticulate#640] opened 2019-11-10 19:12 UTC
As noted in #398, Reticulate seems to truncate full stacktraces.  Note the 'F' on the final line indicating there is more to the stacktrace

```
Detailed traceback: 
  File "<string>", line 4, in <module>
  File /x/y/z/b.py, line 220, in __call__ 
    return_obj = self._function(*args, **kwargs)
  File /x/y/z/base.py, line 166, in b
    return cls.get(*args, **kwargs)
  File /x/y/z/q.py, line 230, in get 
    ...
  File /x/y/z/q.py, line 229, in <listcomp> 
    ....
  File /x/y/z/q.py, line 188, in z
    **kwargs
  F
Calls: runFromEnv ... prepareUpdates -> py_run_string -> py_run_string_impl
```

**Comment by kevinushey** [comment] 2019-11-11 00:24
The problem is that we call `stop(py_fetch_error())` in a lot of places, but R drops overly-long strings sent to stderr. I believe this is the same issue as https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17576, which should be fixed in R-devel.

For comparison:

```
    set.seed(123)
    long <- paste(sample(letters, 10000, TRUE), collapse = "")
    stop(long)
```

You should notice that the long string is truncated, compared to what you get from a "regular" print.

Still, we should consider working around this if possible.

**Comment by skeydan** [comment] 2019-12-09 13:57
@kevinushey I downloaded yesterday's R 3.6.2 pre-release and it looks like the fix

https://github.com/wch/r-source/commit/bc6e559c4940ed18e99ac2fd91d20f01ed186c72

made it there. Given that, do you think we should try thinking of a workaround still?

**Comment by kevinushey** [comment] 2019-12-09 18:24
I think working around this is probably going to be too painful. Let's table this and just instruct users to update R if they require the full traceback.

**Comment by skeydan** [comment] 2019-12-09 20:41
Ok thanks! Closing the issue then.

**Closed by skeydan** 2019-12-09 20:41 UTC
