### ISSUE TITLE
Keras Custom Model Runtime error: unused argument (training = <environment>)

### ISSUE THREAD

**Issue by ifrit98** [rstudio/reticulate#647] opened 2019-11-17 04:51 UTC
Came across this and confirmed in a fresh install of R, rstudio, tensorflow, reticulate, etc., with example code provided by [https://tensorflow.rstudio.com/keras/articles/custom_models.html](url).  

Happens with `tensorflow==2.0.0b1` and `tensorflow==1.15`, as well as both github and CRAN versions of reticulate, keras, and tensorflow R pkgs. 

Code to reproduce:
```{R}
library(keras)

keras_model_simple_mlp <- function(num_classes, 
                                   use_bn = FALSE, use_dp = FALSE, 
                                   name = NULL) {
  
  # define and return a custom model
  keras_model_custom(name = name, function(self) {
    
    # create layers we'll need for the call (this code executes once)
    self$dense1 <- layer_dense(units = 32, activation = "relu")
    self$dense2 <- layer_dense(units = num_classes, activation = "softmax")
    if (use_dp)
      self$dp <- layer_dropout(rate = 0.5)
    if (use_bn)
      self$bn <- layer_batch_normalization(axis = -1)
    
    # implement call (this code executes during training & inference)
    function(inputs, mask = NULL) {
      x <- self$dense1(inputs)
      if (use_dp)
        x <- self$dp(x)
      if (use_bn)
        x <- self$bn(x)
      self$dense2(x)
    }
  })
}


# create the model 
model <- keras_model_simple_mlp(num_classes = 10, use_dp = TRUE)

# compile graph
model %>% compile(
  loss = 'categorical_crossentropy',
  optimizer = optimizer_rmsprop(),
  metrics = c('accuracy')
)

# Generate dummy data
data <- matrix(runif(1000*100), nrow = 1000, ncol = 100)
labels <- matrix(round(runif(1000, min = 0, max = 9)), nrow = 1000, ncol = 1)

# Convert labels to categorical one-hot encoding
one_hot_labels <- to_categorical(labels, num_classes = 10)

# Train the model
model %>% fit(data, one_hot_labels, epochs=10, batch_size=32)
```

Full error msg in Rstudio:
```
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  RuntimeError: in converted code:
    relative to /home/jason/R/x86_64-pc-linux-gnu-library/3.6:

    keras/python/kerastools/model.py:19 call  *
        return self._r_call(inputs, mask, **kwargs)
    reticulate/python/rpytools/call.py:21 python_function  *
        raise RuntimeError(res[kErrorKey])

    RuntimeError: Evaluation error: unused argument (training = <environment>). 
26.
stop(structure(list(message = "RuntimeError: in converted code:\n    relative to /home/jason/R/x86_64-pc-linux-gnu-library/3.6:\n\n    keras/python/kerastools/model.py:19 call  *\n        return self._r_call(inputs, mask, **kwargs)\n    reticulate/python/rpytools/call.py:21 python_function  *\n        raise RuntimeError(res[kErrorKey])\n\n    RuntimeError: Evaluation error: unused argument (training = <environment>).\n", 
    call = py_call_impl(callable, dots$args, dots$keywords), 
    cppstack = structure(list(file = "", line = -1L, stack = c("/home/jason/R/x86_64-pc-linux-gnu-library/3.6/reticulate/libs/reticulate.so(Rcpp::exception::exception(char const*, bool)+0x7a) [0x7f15ecb2e39a]", 
    "/home/jason/R/x86_64-pc-linux-gnu-library/3.6/reticulate/libs/reticulate.so(Rcpp::stop(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x27) [0x7f15ecb2e4f7]",  ... 
25.
wrapper at api.py#237
24.
__call__ at base_layer.py#842
23.
_set_inputs at training.py#2709
22.
_build_model_with_inputs at training.py#2622
21.
_standardize_user_data at training.py#2419
20.
_process_inputs at training_v2.py#594
19.
_process_training_inputs at training_v2.py#547
18.
fit at training_v2.py#224
17.
fit at training.py#728
16.
(structure(function (...) 
{
    dots <- py_resolve_dots(list(...))
    result <- py_call_impl(callable, dots$args, dots$keywords) ... 
15.
do.call(object$fit, args) 
14.
fit.keras.engine.training.Model(., data, one_hot_labels, epochs = 10, 
    batch_size = 32) 
13.
fit(., data, one_hot_labels, epochs = 10, batch_size = 32) 
12.
function_list[[k]](value) 
11.
withVisible(function_list[[k]](value)) 
10.
freduce(value, `_function_list`) 
9.
`_fseq`(`_lhs`) 
8.
eval(quote(`_fseq`(`_lhs`)), env, env) 
7.
eval(quote(`_fseq`(`_lhs`)), env, env) 
6.
withVisible(eval(quote(`_fseq`(`_lhs`)), env, env)) 
5.
model %>% fit(data, one_hot_labels, epochs = 10, batch_size = 32) at keras-model-test.R#49
4.
eval(ei, envir) 
3.
eval(ei, envir) 
2.
withVisible(eval(ei, envir)) 
1.
source("~/git/layer-autoencoder/utils/keras-model-test.R") 
```

My sessionInfo():
```
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] keras_2.2.5.0

loaded via a namespace (and not attached):
 [1] compiler_3.6.1         magrittr_1.5           R6_2.4.1               generics_0.0.2        
 [5] tools_3.6.1            whisker_0.4            base64enc_0.1-3        rappdirs_0.3.1        
 [9] Rcpp_1.0.3             reticulate_1.13.0-9004 tensorflow_2.0.0       zeallot_0.1.0         
[13] jsonlite_1.6           tfruns_1.4   
```

My `tf_config` and `py_config`s
```
> tensorflow::tf_config()
TensorFlow v2.0.0 (~/.local/lib/python3.6/site-packages/tensorflow)
Python v3.6 (/usr/bin/python3)
> reticulate::py_config()
python:         /usr/bin/python3
libpython:      /usr/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6.so
pythonhome:     //usr://usr
version:        3.6.8 (default, Oct  7 2019, 12:59:55)  [GCC 8.3.0]
numpy:          /home/jason/.local/lib/python3.6/site-packages/numpy
numpy_version:  1.17.4
tensorflow:     /home/jason/.local/lib/python3.6/site-packages/tensorflow

python versions found: 
 /usr/bin/python3
 /home/jason/tf1/bin/python
```

**Comment by skeydan** [comment] 2019-11-17 16:21
duplicate of https://github.com/rstudio/keras/issues/929

**Closed** 2019-11-28 08:03 UTC
