### ISSUE TITLE
Error in path.expand(path) : invalid 'path' argument

### ISSUE THREAD

**Issue by ZhongLIFR** [rstudio/reticulate#588] opened 2019-09-02 14:14 UTC
Everything went well until I updated from the version 1.12 to the version 1.13 today,
I can not source any python script any more using your package.
I have spent half a year in this big project, now you tell me that I cannot use it anymore?
SOS SOS SOS help me ...
I have tested all the computers of my colleagues, and I got the same issues.

here is the error:
Error in path.expand(path) : invalid 'path' argument
Calls: import ... conda_list -> unique ->normalizePath ->path.expand

**Comment by ZhongLIFR** [comment] 2019-09-02 14:29
I have tested it in Mac OS, but there is no such problem. This problem is just for Windows System. If  anyone has the package for the version 1.12, please send it to me via 1631845@tongji.edu.cn   Thanks a lot.

**Comment by kevinushey** [comment] 2019-09-02 14:42
Old versions of the package are available at https://cran.r-project.org/src/contrib/Archive/reticulate/

**Comment by jnuvenus** [comment] 2019-09-24 11:38
I got this Error in using reticulate 1.13 too, have you solved this problem or not @ZhongLIFR

**Comment by ZhongLIFR** [comment] 2019-09-24 12:06
Hello Jnuvenus,

I have tried all the solutions that I can find on internet but I failed.
However, I used the package “devtools” to install the version 1.12 after
downloading the Reticulate 1.12 package to  my  own computer.

By the way, if you work in a bank, you’d better ask for permission to
install packages by using “devtools”.

Best wishes,
Zhong

jnuvenus <notifications@github.com>于2019年9月24日 周二下午2:00写道：

**Comment by khaeru** [comment] 2019-09-30 14:33
This may be a duplicate of #571.

**Comment by Timag** [comment] 2019-10-30 13:05
We had the same Problem on a Windows machine with reticulate 1.13 and this helped: https://stackoverflow.com/a/51547674/8538074. 
We didnt go for ".Renviron" file but directly: `setx RETICULATE_PYTHON PATHTODIRECTORY \M`. In our case `PATHTODIRECTORY` was the anaconda directory with the python binary.

**Comment by Timag** [comment] 2019-10-30 13:08
We had the same Problem on a Windows machine with reticulate 1.13 and this helped: https://stackoverflow.com/a/51547674/8538074. 
We didnt go for ".Renviron" file but directly: `setx RETICULATE_PYTHON PATHTODIRECTORY \M`. In our case `PATHTODIRECTORY` was the anaconda directory with the python binary.

Edit: Just noticed. The thread linked by khaeru also includes the solution: https://github.com/rstudio/reticulate/issues/571#issuecomment-518838425.

**Comment by ZhongLIFR** [comment] 2019-10-31 05:11
Hello Tonio, thanks for your reply and suggestions. In fact, I was working
in a huge bank at that time. I did try to change the path. But
unfortunately, I was not authorized to do so. Other people will benefit
from your answer~

**Comment by skeydan** [comment] 2019-11-29 14:55
Closing as this seems to be solved

**Closed by skeydan** 2019-11-29 14:55 UTC
