### ISSUE TITLE
Unwanted type conversion SparklyR + reticulate

### ISSUE THREAD

**Issue by pvieito** [rstudio/reticulate#1360] opened 2023-03-29 08:39 UTC
Hi! I am passing a SparklyR dataframe from R → Python → R, and it seems that it gets implicitly converted to a list so it fails when being used with other functions like `sdf_collect`. For example:

interop.R
```R
send_sparklyr_query <- function(query) {
  library(sparklyr)
  result <- sparklyr::sdf_sql(.DataTools._sparklyr_connection, query)
  return(result)
}
```

interop.py
```python
def python_function_that_calls_sparklyr(query):
  query = some_conversion(query)
  # I got a reference to R `send_sparklyr_query` function in Python:
  return r_interop.send_sparklyr_query(query)
```

main.R
```R
sdf = python_function_that_calls_sparklyr(query)
sdf_collect(sdf)
# Error: Unable to retrieve a spark_connection from object of class list
```

How can I solve this?

**Comment by edgararuiz** [comment] 2023-03-29 17:53
Hi @pvieito , 

Can you share with us the output of the following?

```
class(sdf)

str(sdf)

library(sparklyr)
spark_connection_is_open(spark_connection(sdf))
```

**Comment by pvieito** [comment] 2023-03-31 18:27
Sure!

```
Debug> class(sdf)
[1] "list"

Debug> str(sdf)
List of 6
 $ src               :List of 1
  ..$ con:List of 13
  .. ..$ master      : chr "local[10]"
  .. ..$ method      : chr "shell"
  .. ..$ app_name    : chr "FootFall-R"
  .. ..$ config      :List of 25
  .. .. ..$ spark.kryo.registrator                                     : chr "org.apache.sedona.viz.core.Serde.SedonaVizKryoRegistrator"
  .. .. ..$ spark.serializer                                           : chr "org.apache.spark.serializer.KryoSerializer"
  .. .. ..$ spark.env.SPARK_LOCAL_IP.local                             : chr "127.0.0.1"
  .. .. ..$ sparklyr.connect.csv.embedded                              : chr "^1.*"
  .. .. ..$ spark.sql.legacy.utcTimestampFunc.enabled                  : logi TRUE
  .. .. ..$ sparklyr.connect.cores.local                               : int 10
  .. .. ..$ spark.sql.shuffle.partitions.local                         : int 10
  .. .. ..$ spark.sql.adaptive.enabled                                 : logi TRUE
  .. .. ..$ spark.sql.adaptive.logLevel                                : chr "ERROR"
  .. .. ..$ spark.sql.adaptive.coalescePartitions.enabled              : logi TRUE
  .. .. ..$ spark.sql.adaptive.coalescePartitions.initialPartitionNum  : chr "500"
  .. .. ..$ spark.sql.adaptive.coalescePartitions.minPartitionNum      : chr "100"
  .. .. ..$ spark.sql.adaptive.advisoryPartitionSizeInBytes            : chr "32M"
  .. .. ..$ spark.sql.adaptive.skewJoin.enabled                        : logi TRUE
  .. .. ..$ spark.sql.adaptive.skewJoin.skewedPartitionFactor          : chr "3"
  .. .. ..$ spark.sql.adaptive.skewJoin.skewedPartitionThresholdInBytes: chr "100M"
  .. .. ..$ spark.sql.sources.partitionOverwriteMode                   : chr "dynamic"
  .. .. ..$ spark.jars.packages                                        : chr "org.apache.sedona:sedona-python-adapter-3.0_2.12:1.3.1-incubating,org.datasyslab:geotools-wrapper:1.3.0-27.2"
  .. .. ..$ spark.executor.memory                                      : chr "70g"
  .. .. ..$ spark.driver.memory                                        : chr "50g"
  .. .. ..$ spark.memory.offHeap.size                                  : chr "16g"
  .. .. ..$ spark.driver.extraJavaOptions                              : chr "-Dderby.stream.error.file=/private/var/folders/98/60900k517wxfb4b41l3xrc400000gn/T/F31A4A20-B438-4F0C-A4DA-2549"| __truncated__
  .. .. ..$ spark.sql.legacy.timeParserPolicy                          : chr "LEGACY"
  .. .. ..$ sparklyr.shell.name                                        : chr "FootFall-R"
  .. .. ..$ sparklyr.shell.driver-memory                               : chr "2g"
  .. ..$ state       :<environment: 0x116ed5c60> 
  .. ..$ extensions  :List of 6
  .. .. ..$ jars              : list()
  .. .. ..$ packages          : chr [1:4] "org.apache.sedona:sedona-spark-shaded-3.0_2.12:1.4.0" "org.apache.sedona:sedona-viz-3.0_2.12:1.4.0" "org.datasyslab:geotools-wrapper:1.4.0-28.2" "edu.ucar:cdm-core:5.4.2"
  .. .. ..$ initializers      :List of 1
  .. .. .. ..$ :<function make_python_function.<locals>.python_function at 0x294f74670>
  .. .. ..$ catalog_jars      : list()
  .. .. ..$ repositories      : chr "https://artifacts.unidata.ucar.edu/repository/unidata-all"
  .. .. ..$ dbplyr_sql_variant:List of 3
  .. .. .. ..$ scalar   :List of 7
  .. .. .. .. ..$ ST_Buffer                  :<function make_python_function.<locals>.python_function at 0x29120c670>
  .. .. .. .. ..$ ST_PrecisionReduce         :<function make_python_function.<locals>.python_function at 0x2955154c0>
  .. .. .. .. ..$ ST_SimplifyPreserveTopology:<function make_python_function.<locals>.python_function at 0x295515550>
  .. .. .. .. ..$ ST_GeometryN               :<function make_python_function.<locals>.python_function at 0x2955155e0>
  .. .. .. .. ..$ ST_InteriorRingN           :<function make_python_function.<locals>.python_function at 0x295515670>
  .. .. .. .. ..$ ST_AddPoint                :<function make_python_function.<locals>.python_function at 0x295515700>
  .. .. .. .. ..$ ST_RemovePoint             :<function make_python_function.<locals>.python_function at 0x295515790>
  .. .. .. ..$ aggregate: list()
  .. .. .. ..$ window   : list()
  .. ..$ spark_home  : chr "/Users/pvieito/Library/Python/3.9/lib/python/site-packages/pyspark"
  .. ..$ backend     : int 4
  .. ..$ monitoring  : int 5
  .. ..$ gateway     : int 3
  .. ..$ output_file : chr "/var/folders/98/60900k517wxfb4b41l3xrc400000gn/T//RtmpKMwE3q/file731654954d4a_spark.log"
  .. ..$ sessionId   : num 1459
  .. ..$ home_version: chr "3.3.2"
 $ lazy_query        :List of 5
  ..$ x         : chr "tquxwsnrawmbwuhiitramewwzzozrdrb"
  ..$ vars      : chr "retailer_id"
  ..$ group_vars: list()
  ..$ order_vars: NULL
  ..$ frame     : NULL
 $ sdf_cache_state   :<environment: 0x116fbea20> 
 $ spark_dataframe   :<function make_python_function.<locals>.python_function at 0x2955158b0>
 $ schema_cache_state:<environment: 0x116fbdee8> 
 $ schema            :<function make_python_function.<locals>.python_function at 0x295515940>

Debug> spark_connection_is_open(spark_connection(sdf))
Error: Unable to retrieve a spark_connection from object of class list
Show stack trace

Debug> spark_connection(sdf)
Error: Unable to retrieve a spark_connection from object of class list
Show stack trace
```

**Comment by pvieito** [comment] 2023-03-31 18:30
And this is for the Spark dataframe before transversing the R→Python→R boundary:

```
Debug> class(sdf)
[1] "tbl_spark" "tbl_sql"   "tbl_lazy"  "tbl"      

Debug> str(sdf)
List of 6
 $ retailer_id:List of 1
  ..$ con:List of 13
  .. ..$ master      : chr "local[10]"
  .. ..$ method      : chr "shell"
  .. ..$ app_name    : chr "FootFall-R"
  .. ..$ config      :List of 25
  .. .. ..$ spark.kryo.registrator                                     : chr "org.apache.sedona.viz.core.Serde.SedonaVizKryoRegistrator"
  .. .. ..$ spark.serializer                                           : chr "org.apache.spark.serializer.KryoSerializer"
  .. .. ..$ spark.env.SPARK_LOCAL_IP.local                             : chr "127.0.0.1"
  .. .. ..$ sparklyr.connect.csv.embedded                              : chr "^1.*"
  .. .. ..$ spark.sql.legacy.utcTimestampFunc.enabled                  : logi TRUE
  .. .. ..$ sparklyr.connect.cores.local                               : int 10
  .. .. ..$ spark.sql.shuffle.partitions.local                         : int 10
  .. .. ..$ spark.sql.adaptive.enabled                                 : logi TRUE
  .. .. ..$ spark.sql.adaptive.logLevel                                : chr "ERROR"
  .. .. ..$ spark.sql.adaptive.coalescePartitions.enabled              : logi TRUE
  .. .. ..$ spark.sql.adaptive.coalescePartitions.initialPartitionNum  : chr "500"
  .. .. ..$ spark.sql.adaptive.coalescePartitions.minPartitionNum      : chr "100"
  .. .. ..$ spark.sql.adaptive.advisoryPartitionSizeInBytes            : chr "32M"
  .. .. ..$ spark.sql.adaptive.skewJoin.enabled                        : logi TRUE
  .. .. ..$ spark.sql.adaptive.skewJoin.skewedPartitionFactor          : chr "3"
  .. .. ..$ spark.sql.adaptive.skewJoin.skewedPartitionThresholdInBytes: chr "100M"
  .. .. ..$ spark.sql.sources.partitionOverwriteMode                   : chr "dynamic"
  .. .. ..$ spark.jars.packages                                        : chr "org.apache.sedona:sedona-python-adapter-3.0_2.12:1.3.1-incubating,org.datasyslab:geotools-wrapper:1.3.0-27.2"
  .. .. ..$ spark.executor.memory                                      : chr "70g"
  .. .. ..$ spark.driver.memory                                        : chr "50g"
  .. .. ..$ spark.memory.offHeap.size                                  : chr "16g"
  .. .. ..$ spark.driver.extraJavaOptions                              : chr "-Dderby.stream.error.file=/private/var/folders/98/60900k517wxfb4b41l3xrc400000gn/T/F31A4A20-B438-4F0C-A4DA-2549"| __truncated__
  .. .. ..$ spark.sql.legacy.timeParserPolicy                          : chr "LEGACY"
  .. .. ..$ sparklyr.shell.name                                        : chr "FootFall-R"
  .. .. ..$ sparklyr.shell.driver-memory                               : chr "2g"
  .. ..$ state       :<environment: 0x116ed5c60> 
  .. ..$ extensions  :List of 6
  .. .. ..$ jars              : chr(0) 
  .. .. ..$ packages          : chr [1:4] "org.apache.sedona:sedona-spark-shaded-3.0_2.12:1.4.0" "org.apache.sedona:sedona-viz-3.0_2.12:1.4.0" "org.datasyslab:geotools-wrapper:1.4.0-28.2" "edu.ucar:cdm-core:5.4.2"
  .. .. ..$ initializers      :List of 1
  .. .. .. ..$ :function (sc)  
  .. .. .. .. ..- attr(*, "srcref")= 'srcref' int [1:8] 1 1 23 1 1 1 1 23
  .. .. .. .. .. ..- attr(*, "srcfile")=Classes 'srcfilecopy', 'srcfile' <environment: 0x121bd4748> 
  .. .. .. .. .. .. ..- attr(*, "rwr_virtual_file")=<externalptr> 
  .. .. .. .. .. .. ..- attr(*, "rwr_line_offset")= int 0
  .. .. .. .. .. .. ..- attr(*, "rwr_first_line_offset")= int 0
  .. .. ..$ catalog_jars      : chr(0) 
  .. .. ..$ repositories      : chr "https://artifacts.unidata.ucar.edu/repository/unidata-all"
  .. .. ..$ dbplyr_sql_variant:List of 3
  .. .. .. ..$ scalar   :List of 7
  .. .. .. .. ..$ ST_Buffer                  :function (geometry, buffer)  
  .. .. .. .. ..$ ST_PrecisionReduce         :function (geometry, precision)  
  .. .. .. .. ..$ ST_SimplifyPreserveTopology:function (geometry, distance_tolerance)  
  .. .. .. .. ..$ ST_GeometryN               :function (geometry, n)  
  .. .. .. .. ..$ ST_InteriorRingN           :function (geometry, n)  
  .. .. .. .. ..$ ST_AddPoint                :function (geometry, point, position = NULL)  
  .. .. .. .. ..$ ST_RemovePoint             :function (geometry, position = NULL)  
  .. .. .. ..$ aggregate: list()
  .. .. .. ..$ window   : list()
  .. ..$ spark_home  : chr "/Users/pvieito/Library/Python/3.9/lib/python/site-packages/pyspark"
  .. ..$ backend     : 'sockconn' int 4
  .. .. ..- attr(*, "conn_id")=<externalptr> 
  .. ..$ monitoring  : 'sockconn' int 5
  .. .. ..- attr(*, "conn_id")=<externalptr> 
  .. ..$ gateway     : 'sockconn' int 3
  .. .. ..- attr(*, "conn_id")=<externalptr> 
  .. ..$ output_file : chr "/var/folders/98/60900k517wxfb4b41l3xrc400000gn/T//RtmpKMwE3q/file731654954d4a_spark.log"
  .. ..$ sessionId   : num 1459
  .. ..$ home_version: chr "3.3.2"
  .. ..- attr(*, "class")= chr [1:3] "spark_connection" "spark_shell_connection" "DBIConnection"
  ..- attr(*, "class")= chr [1:3] "src_spark" "src_sql" "src"
 $ NA:List of 5
  ..$ x         : 'ident' chr "tquxwsnrawmbwuhiitramewwzzozrdrb"
  ..$ vars      : chr "retailer_id"
  ..$ group_vars: chr(0) 
  ..$ order_vars: NULL
  ..$ frame     : NULL
  ..- attr(*, "class")= chr [1:3] "lazy_base_remote_query" "lazy_base_query" "lazy_query"
 $ NA:<environment: 0x116fbea20> 
 $ NA:function (self, spark_dataframe_impl)  
 $ NA:<environment: 0x116fbdee8> 
 $ NA:function (self, schema_impl, expand_nested_cols, expand_struct_cols)  
 - attr(*, "class")= chr [1:4] "tbl_spark" "tbl_sql" "tbl_lazy" "tbl"

Debug> spark_connection_is_open(spark_connection(sdf))
[1] TRUE
```

**Comment by pvieito** [comment] 2023-04-15 07:43
@edgararuiz Hi! Any update about this issue?

**Comment by pvieito** [comment] 2023-04-20 15:27
@edgararuiz Hey! Yes, the issue seems generic:

```R
send_sparklyr_query <- function(query) {
  result <- list()
  class(result) <- "not_real"
  return(result)
}
```

```R
> sdf <- python_function_that_calls_sparklyr("SELECT 1")
> class(sdf)
[1] "list"
> str(sdf)
 list()
 ```

**Comment by edgararuiz** [comment] 2023-04-20 20:26
@pvieito - Can you share with me more info from your python script? For example, where does `r_interop` object comes from? Is there a more complete script you can give me so I can reproduce?

**Comment by t-kalinowski** [comment] 2023-04-21 12:54
If I'm understanding the issue, it looks like the `tbl_spark` object is not used at all in Python, and merely needs to be passed through the python runtime. You could protect the R object from any conversion in python by wrapping it in a py_capsule with a custom `r_to_py()` method. 
Note, this will only work w/ the development branch of reticulate:

```r
r_to_py.tbl_spark <- function(x, convert = FALSE) {
  stopifnot(isFALSE(convert))
  reticulate:::py_capsule(x)
}
```

Depending on how you're running the python code, you may need to manually register the S3 method

```r
registerS3method("r_to_py", "tbl_spark", r_to_py.tbl_spark)
```
@pvieito Can you please try that and report if it works?

**Comment by brownag** [comment] 2023-08-15 23:18
Hello! I recently encountered a similar (inverse) issue where I need to retain the subclass of an object result that inherits from `"python.builtin.list"` in R. The object's full class information needs to persist through Python->R->Python in my case.

The problem seems to have appeared with the changes in {reticulate} 1.29. Reverting to 1.28 gave the old/expected behavior.

Similar to OP the conversion to an R list object is not a desired result because the object will be passed back to a python function. Returning an R list loses information, interfering with Python code that expects the specific subclass. However, the problem appears to be resolved by defining a custom S3 `py_to_r()` method:

```r
#' @description `py_to_r(<rosetta.rosetta.SoilData>)`: Wrapper S3 method for SoilData objects to prevent automatic conversion of SoilData (subclass of `"python.builtin.list"`) to an R `"list"`
#' @importFrom reticulate py_to_r
#' @export
#' @rdname SoilDataFromArray
py_to_r.rosetta.rosetta.SoilData <- function(x) {
  # do nothing; fix for https://github.com/ncss-tech/rosettaPTF/issues/8
  x
}
```

Using above roxygen tags (importing `reticulate::py_to_r`, and exporting custom S3 method) appears to update the NAMESPACE and documentation as intended.

I am happy with the above solution, but if you would like me to file a new issue or provide a reproducible example I can do that.

**Comment by t-kalinowski** [comment] 2023-08-16 11:15
Thanks for reporting @brownag! The solution of adding a custom `r_to_py()` method is good.
Whether to convert subclassed Python `lists and `dict`s to R lists is an issue that's come up a few times (fortunately, not very frequently). Regardless of whether reticulate converts or doesn't convert, there are tradeoffs. 

The intent of the Python class author varies. Sometimes, the fact that the dict or list is subclassed is meant to be invisible to the end user (e.g., `wrapt.ProxyObject`, as used by `tensor flow._DictWrapper`), and sometimes, the subclassed dict or list adds user facing methods (https://github.com/rstudio/reticulate/issues/1429).

Right now, reticulate converts automatically, and if you want to avoid conversion you can pass `convert = TRUE` to `import(), or call `r_to_py()` (as you mention).

The practice of subclassing a base container in Python is relatively uncommon right now, if the conversation behavior starts being more of an issue, we can change the default.

**Comment by brownag** [comment] 2023-08-16 16:00
Great, thanks @t-kalinowski! I didn't realize `convert=FALSE` could be passed to `import()`. 

I think `r_to_py()` on its own doesn't cover it, as this loses the subclass information, but for now I am fine with this targeted `py_to_r()` method for the specific class in question.

**Closed** 2024-01-30 20:15 UTC
