### ISSUE TITLE
`import()` fails during the first R session when RStudio opens/restarts; succeeds in every subsequent session

### ISSUE THREAD

**Issue by daattali** [rstudio/reticulate#1357] opened 2023-03-23 19:50 UTC
(Windows 10, RStudio build 576, reticulate version 1.27)

I've installed a python package using 

```r
reticulate::py_install("dominodatalab-data", pip = TRUE, method = "virtualenv")
```

I then try to import:

```r
reticulate::import("domino_data.data_sources")
```

When I open a new RStudio, this consistently results in

```r
Error in py_module_import(module, convert = convert) : 
  ImportError: DLL load failed while importing lib: The specified procedure could not be found.
```

If I restart the R session (ctrl+shift+F10), then the import works. Every time I restart the session, it will still work, but it did not work until I restarted the session once.

If I "Terminate R" from the menu (*Session* -> *Terminate R*), then it will go back to failing with the same error, until I restart the R session.

Attaching a video to show.

https://www.loom.com/share/70c22e161ec248e7b8a79fc928d452c2

**Comment by t-kalinowski** [comment] 2023-03-30 17:52
I'll take a look.

**Comment by t-kalinowski** [comment] 2023-03-30 18:07
Hi, I'm unable to reproduce on Windows 10 with Rstudio 2023.03.0 Build 386 (the current release), and reticulate (tried both dev and cran version). 

How did you install python? I'm tested with Python installed via the official installers from www.python.org

**Comment by t-kalinowski** [comment] 2023-03-30 18:14
I also tried with the latest daily build of RStudio (2023.05.0 Build 164) and was unable to reproduce.

**Comment by t-kalinowski** [comment] 2023-03-30 18:22
You shouldn't need to uninstall, multiple python versions can be installed alongside each other, and you can unambiguously tell reticulate which one to use by setting `RETICULATE_PYTHON` before reticulate initializes. You can run installers from `python.org` manually, or try `reticulate::install_python()`

**Comment by t-kalinowski** [comment] 2023-03-30 18:36
Occasionally there are some (unavoidable) binary incompatibilities between conda and R. To see if that's the case here I just tried w/ Python from `install_miniconda()` and was also unable to reproduce the issue that way.

**Comment by dfalbel** [comment] 2023-08-14 13:06
@daattali were you able to fix the problem?

As Tomasz suggested, it's possibly a binary incompatibility between conda Python installation and R. We now recommend using Python virtaul environments, and the new CRAN release of reticulate (v1.31) will prefer those installations. 

Let us know if we can provide additional help.

**Comment by daattali** [comment] 2023-08-14 13:57
The problem persisted for months, even after installing new RStudio versions and R versions. I no longer have access to this project so I won't be able to provide any more input here.

**Comment by dfalbel** [comment] 2023-08-14 14:01
Sorry to hear that :(. Unfortunatelly, I don't think we have enough data to reproduce the problem. I'm going to close the issue, please reopen or open a new issue if you face this problem again. Thanks you!

**Closed by dfalbel** 2023-08-14 14:01 UTC
Labels: reprex

**Comment by t-kalinowski** [comment] 2023-08-14 14:04
Looking back over the thread, my best guess about what was happening is that the IDE was inadvertently forcing reticulate to initialize the "wrong" python before user code had had a chance to run. There were some other fixes of this nature in the IDE since this issue was first opened. Sorry you ran into this issue.

**Comment by upgradedavid** [comment] 2024-03-13 18:20
I actually have a similar issue here on Ubuntu. I'm running a local Python version. Running the app via clicking "Run App" with fresh R session does not work. It works, however, if I manually run these lines from the app:

`reticulate::use_python("/home/david/miniconda3/bin/python3")
anarci <- reticulate::import("anarci")
library(reticulate)`
