### ISSUE TITLE
Error when trying to install Python 3.12

### ISSUE THREAD

**Issue by edgararuiz** [rstudio/reticulate#1512] opened 2023-12-11 19:20 UTC
```r
> install_python("3.12:latest")
+ /opt/homebrew/bin/pyenv update
Error in pyenv_resolve_latest_patch(version, installed = FALSE, pyenv = pyenv) : 
  Python release version '3.12' not found. Run `install_python(list = TRUE)` to see available versions.
```

**Comment by t-kalinowski** [comment] 2024-01-30 16:11
Can't reproduce the error. Closing for now - if we see this again we can reopen the issue.

**Closed by t-kalinowski** 2024-01-30 16:11 UTC
