### ISSUE TITLE
invalid 'envir' argument when importing module via R markdown

### ISSUE THREAD

**Issue by loicdtx** [rstudio/reticulate#828] opened 2020-08-24 17:11 UTC
I just installed the dev version of reticulate and I'm failing to run some python code via R markdown.

Here's a simplified notebook that generates the error on my system.

``````
---
title: "R Notebook"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---


Commands used to setup the virtualenv
```{bash, eval=FALSE}
# Create python3 virtualenv with virtualenvwrapper
mkvirtualenv -p python3 md-test
# Install skimage
pip install scikit-image
# Test import
python -c "from skimage.io import imread"
```

Reticulate setup
```{r setup, include=FALSE}
library(reticulate)
use_virtualenv('/home/loic/.virtualenvs/md-test', required = TRUE)
```

Try importing imread
```{python, include=FALSE}
from skimage.io import imread
```
``````

When I knit the document to either output format, I get the following errror:

```
Quitting from lines 27-28 (debug_reticulate.Rmd) 
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  RuntimeError: Evaluation error: invalid 'envir' argument.

Detailed traceback: 
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/loic/R/x86_64-pc-linux-gnu-library/4.0/reticulate/python/importhook/loader.py", line 85, in exec_module
    mod = self.loader.exec_module(module, *args, **kwargs)
  File "/home/loic/.virtualenvs/md-test/lib/python3.6/site-packages/skimage/io/__init__.py", line 11, in <module>
    from ._io import *
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/loic/R/x86_64-pc-linux-gnu-library/4.0/reticulate/python/importhook/loader.py", line 85, in exec_module
    mod = sel
Calls: <Anonymous> ... py_capture_output -> force -> <Anonymous> -> py_call_impl
Execution halted
```

<details>
<summary>sessionInfo()</summary>
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reticulate_1.16-9000

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5      knitr_1.29      magrittr_1.5    hms_0.5.3       bit_4.0.3       lattice_0.20-41 rlang_0.4.7     stringr_1.4.0   blob_1.2.1     
[10] tools_4.0.2     RPostgres_1.2.0 grid_4.0.2      xfun_0.16       DBI_1.1.0       htmltools_0.5.0 yaml_2.2.1      bit64_4.0.2     digest_0.6.25  
[19] Matrix_1.2-18   base64enc_0.1-3 vctrs_0.3.2     evaluate_0.14   rmarkdown_2.3   stringi_1.4.6   compiler_4.0.2  jsonlite_1.7.0  pkgconfig_2.0.3
</details>

**Comment by kevinushey** [comment] 2020-08-24 17:37
Thanks for the bug report! I'll take a look today.

**Comment by kevinushey** [comment] 2020-08-24 17:50
Should now be fixed in the development version of `reticulate` -- please let me know if you encounter any more issues.

**Comment by loicdtx** [comment] 2020-08-25 09:44
Thanks for the quick fix @kevinushey . It appears to work for that particular import, but I'm hitting a similar issue with another module.

running `import torch` in a python code block returns the following error. I installed torch with pip, similarly to the initial example. 

What's strange also is that this markdown document was compiling flowlessly about a month ago on a different machine with roughly the same configuration as the one I'm using right now.

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  AttributeError: module 'torch._VF' has no attribute 'threshold_'

Detailed traceback: 
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/loic/R/x86_64-pc-linux-gnu-library/4.0/reticulate/python/importhook/loader.py", line 85, in exec_module
    mod = self.loader.exec_module(module, *args, **kwargs)
  File "/home/loic/.virtualenvs/md-test/lib/python3.6/site-packages/torch/__init__.py", line 448, in <module>
    from .functional import *
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/loic/R/x86_64-pc-linux-gnu-library/4.0/reticulate/python/importhook/loader.py", line 85, in exec_module
   
Calls: <Anonymous> ... py_capture_output -> force -> <Anonymous> -> py_call_impl
Execution halted
```

**Comment by kevinushey** [comment] 2020-08-25 16:16
Can you please provide a reproducible example?

**Comment by loicdtx** [comment] 2020-08-25 21:18
@kevinushey , I wish... But I tried to setup a more "neutral" environment using docker to investigate the problem and create something reproducible. I wasn't able to reproduce any of the errors. Everything just worked fine with the stable version of `reticulate`.  Either the "small differences" between the two systems (python version, pip version, virtualenv version, etc...) explain that it works in one case and not in the other, or there is something "wrong" with my system which would invalidate the whole issue (and perhaps you should reverse your fix)...

Let me know if you want to keep investigating and require further details.

**Comment by loicdtx** [comment] 2020-08-25 21:41
I spoke too fast, it fails even on the docker experiment, but only when using the github `HEAD`. The stable version works fine.
To reproduce via docker.

Start container
```
docker run -d --name reticulate -p 8787:8787 -e PASSWORD=pwd -e ROOT=TRUE rocker/rstudio
```

Visit [localhost:8787](localhost:8787)
```
# In the rstudio terminal
sudo apt install python3-pip
python3 -m pip install virtualenv
mkdir /home/rstudio/.virtualenvs
python3 -m virtualenv /home/rstudio/.virtualenvs/reticulate
source /home/rstudio/.virtualenvs/reticulate/bin/activate
pip install torch # warning, heavy package
```

R packages setup.
```
install.packages(c("knitr", "rmarkdown", "devtools"))
devtools::install_github('rstudio/reticulate')
tinytex::install_tinytex()
```

Notebook:
``````
---
title: "R Notebook"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---

Reticulate setup
```{r setup, include=FALSE}
library(reticulate)
use_virtualenv('/home/rstudio/.virtualenvs/reticulate', required = TRUE)
```

Try importing torch
```{python, include=FALSE}
import torch
```
``````

Knit the notebook

**Comment by kevinushey** [comment] 2020-08-26 17:19
Thank you! Here is a minimal example that works for me even without Docker (on macOS):

```
library(reticulate)

virtualenv_create(
  envname  = "torch",
  python   = "/usr/local/bin/python3.8",
  packages = c("numpy", "torch"),
  system_site_packages = FALSE
)

use_virtualenv("torch", required = TRUE)
py_config()

torch <- import("torch")
```

**Comment by kevinushey** [comment] 2020-08-26 17:24
This is unfortunate. We recently added a Python module (https://pypi.org/project/importhook/) to `reticulate`, to "hook" modules on load, so we can detect when Python modules are loaded. Unfortunately, the way this module works seems to interfere with the way `torch` is loaded.

Back to the drawing board...

**Comment by kevinushey** [comment] 2020-09-15 23:36
This should be fixed now -- rather than hacking the Python loaders, we do it the old fashioned way -- by overriding the `__import__` builtin.

Still a hack, but a better one!

**Closed by kevinushey** 2020-09-15 23:36 UTC
