### ISSUE TITLE
Error at compile(model, ...) on Win10: "TypeError: __init__() missing 1 required positional argument: 'args'"

### ISSUE THREAD

**Issue by qdread** [rstudio/reticulate#1483] opened 2023-09-18 14:45 UTC
I am unable to reproduce the results in the [vignette](https://cran.r-project.org/web/packages/keras/vignettes/) due to an error at the `compile()` step:

### Error message from `compile()`

```
Error in py_call_impl(callable, call_args$unnamed, call_args$named) :
TypeError: __init__() missing 1 required positional argument: 'args'
Run `reticulate::py_last_error()` for details.
```

### Output of `reticulate::py_last_error()`

```
── Python Exception Message ──────────────────────────────────────────────────────────────────────────────────────────────────────────
TypeError: 'Sequential' object is not subscriptable

── R Traceback ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
     ▆
  1. └─.rs.environment.isSuspendable()
  2.   ├─base::tryCatch(...)
  3.   │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)
  4.   │   └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
  5.   │     └─base (local) doTryCatch(return(expr), name, parentenv, handler)
  6.   └─.rs.environment.isSuspendableImpl(globalenv(), 1L)
  7.     └─.rs.environment.isSuspendableImpl(value[[key]], depth + 1L)
  8.       ├─.rs.environment.isSuspendableImpl(value[[i]], depth + 1L)
  9.       ├─value[[i]]
 10.       └─reticulate:::`[[.python.builtin.object`(value, i)
 11.         └─reticulate:::py_get_attr_or_item(x, name, FALSE)
 12.           └─reticulate::py_get_item(x, name)
 13.             └─reticulate:::py_get_item_impl(x, key, silent)
 ```

### Output of `reticulate::py_config()`

```
python:         C:/Users/qdread/Documents/.virtualenvs/r-tensorflow/Scripts/python.exe
libpython:      C:/Users/qdread/AppData/Local/r-reticulate/r-reticulate/pyenv/pyenv-win/versions/3.9.13/python39.dll
pythonhome:     C:/Users/qdread/Documents/.virtualenvs/r-tensorflow
version:        3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/qdread/Documents/.virtualenvs/r-tensorflow/Lib/site-packages/numpy
numpy_version:  1.24.3
tensorflow:     C:\Users\qdread\DOCUME~1\VIRTUA~1\R-TENS~1\lib\site-packages\tensorflow\__init__.p

NOTE: Python version was forced by import("tensorflow")
```

### Output of `sessionInfo()`

```
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                           LC_TIME=English_United States.utf8    

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] keras_2.13.0.9000

loaded via a namespace (and not attached):
 [1] Matrix_1.6-0           gtable_0.3.3           jsonlite_1.8.7         dplyr_1.1.2            compiler_4.3.1        
 [6] tidyselect_1.2.0       Rcpp_1.0.11            zeallot_0.1.0          xml2_1.3.5             tensorflow_2.13.0.9000
[11] tfruns_1.5.1           scales_1.2.1           png_0.1-8              yaml_2.3.7             fastmap_1.1.1         
[16] here_1.0.1             reticulate_1.32.0.9000 lattice_0.21-8         ggplot2_3.4.2          R6_2.5.1              
[21] generics_0.1.3         knitr_1.43             ggtext_0.1.2           tibble_3.2.1           rprojroot_2.0.3       
[26] munsell_0.5.0          pillar_1.9.0           rlang_1.1.1            utf8_1.2.3             xfun_0.39             
[31] cli_3.6.1              magrittr_2.0.3         digest_0.6.33          grid_4.3.1             gridtext_0.1.5        
[36] rstudioapi_0.15.0      base64enc_0.1-3        lifecycle_1.0.3        vctrs_0.6.3            evaluate_0.21         
[41] glue_1.6.2             whisker_0.4.1          fansi_1.0.4            colorspace_2.1-0       rmarkdown_2.23        
[46] tools_4.3.1            pkgconfig_2.0.3        htmltools_0.5.5       
```

**Comment by t-kalinowski** [comment] 2023-09-18 16:01
Duplicate of [rstudio/tensorflow](https://github.com/rstudio/tensorflow/issues/582)

Please (re)try the latest development version, this should be fixed now.

---

Side note, the wrong `─.rs.environment.isSuspendable()` in the traceback printed from `py_last_error()` is fixed in the development version of R Studio (https://dailies.rstudio.com/links/#daily-builds). Alternatively, you can work around it by calling `py_last_error()` before the IDE has had a chance to inspect the object, e.g., in one line: `try(<reticulate-call-that-errors>); reticulate::py_last_error()`

**Closed** 2023-09-18 22:40 UTC
